version: '{build}'

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  except:
    - gh-pages

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

dotnet_csproj:
  patch: false

image: Ubuntu2004

install:
  - git submodule update --init --recursive
  - dotnet tool restore

build_script:
  - pwsh: if ($env:APPVEYOR_REPO_TAG_NAME) { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME -replace "v")" }
  - dotnet cake build.cake --bootstrap
  - dotnet cake build.cake --pack

test: off

artifacts:
  - path: ./build/*.zip
  - path: ./build/*.tar.gz
  - path: ./build/*.nupkg
  - path: ./build/*.snupkg

deploy:
  #  - provider: NuGet
  #    artifact: /.*(\.|\.s)nupkg/
  #    on:
  #      branch: master
  #    api_key:
  #      secure: 4OHXl+m1KVi60hB1j54MpdP8tVv0UNfkdF4rVP+2AhAjN4a2MVT+Bl90gJZ96xHF

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_PROJECT_NAME) $(APPVEYOR_BUILD_VERSION)
    description: 'DRAFT'
    auth_token:
      secure: vyQ+zijv9g99wEgIdSC8uPSlnFvH3KZiD0yE7mNA3r3z2OY4lTEF6bpuUvtjoaM3
    artifact: /.*/
    draft: true
    on:
      APPVEYOR_REPO_TAG: true

only_commits:
  files:
    - appveyor.yml
    - build.cake
    - src/**/*
    - .gitmodules
