version: '{build}'

environment:
  IMPOSTOR_VERSION: '1.1.0'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  except:
  - gh-pages

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

dotnet_csproj:
  patch: false

image: Visual Studio 2019 Preview

install:
  - git submodule update --init --recursive
  - ps: dotnet tool restore

build_script:
  - ps: dotnet cake build.cake --bootstrap
  - ps: dotnet cake build.cake --pack

test: off

artifacts:
  - path: ./build/*.zip
  - path: ./build/*.nupkg
  - path: ./build/*.snupkg

deploy:
  - provider: NuGet
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: dev
    api_key:
      secure: 4OHXl+m1KVi60hB1j54MpdP8tVv0UNfkdF4rVP+2AhAjN4a2MVT+Bl90gJZ96xHF

only_commits:
  files:
    - appveyor.yml
    - build.cake
    - src/**/*
    - .gitmodules
