name: Build

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - '.gitmodules'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - '.gitmodules'
      - '.github/workflows/main.yml'

jobs:
  build-client:
    name: Build Client
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.402
      - name: Build Impostor.Client
        run: dotnet build ./src/Impostor.Client/Impostor.Client.WinForms/Impostor.Client.WinForms.csproj -c Release
  build-server:
    name: Build Server
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.1.20452.10
      - name: Install dependencies
        run: dotnet restore ./src
      - name: Build Impostor.Server
        run: dotnet build --no-restore -c Release -f net5.0 ./src/Impostor.Server/Impostor.Server.csproj /p:PublishTrimmed=false
      - name: Test
        run: dotnet test --no-restore -v normal -f net5.0 ./src
